### ISSUE TITLE
Request: "startedApp" as additional attribute 

### ISSUE THREAD

**Issue by Pe-MaKer** [gerard33/home-assistant#3]
Thanks for all of your work!
Some of my automations already rely on the attibutes from your component.

When I switch to a different channel, I let google home tell me which show is currently running, when it started and when it ends.
For this I had to split the three information from the "media_series_title" attribute into three different sensors. 
```
sensor:
  - platform: template
    sensors:
      sony_tv_sendung:
        value_template: "{{ states.media_player.sonyfernseher.attributes['media_series_title'].split('[')[0] | default('gerade nichts') }}"
        friendly_name: "Sendung"
      sony_tv_beginn:
        value_template: "{{ states.media_player.sonyfernseher.attributes['media_series_title'].split('[')[1].split(' - ')[0] | default('gerade nichts') }}"
        friendly_name: "Anfang"
      sony_tv_sendeschluss:
        value_template: "{{ states.media_player.sonyfernseher.attributes['media_series_title'].split('[')[1].split(' - ')[1].split(']')[0] | default('gerade nichts') }}"
        friendly_name: "Ende"
```

Not elegant, but functional. Since you want to work on a progress bar for the current show anyway, I also hope for improvements for my purposes.
But what I miss completely is the information which app is currently active. Prime Video, Youtube, Kodi.

Do you have any idea how we can use also this information in Home Assistant?
